README.md

A minimal readme file for the first release.

update minimal README

---

polyply/src/apply_links.py
polyply/tests/test_apply_links.py

Adding the replace syntax to polyply for making PEGylated lipids and such

add replace syntax to links

---

polyply/data/martini2_polymers/links.ff

Data files for making PEGylated lipids in M2 for DPPC  POPC DOPC DPPE

input files for M2 PEGylated lipids and OHTer or PEO residue

---

polyply/src/gen_coords.py
polyply/src/gen_itp.py

new file writing using the deferred file writer and compatible with master

use deferred file-writer

---

polyply/src/top_parser.py
polyply/tests/test_top_parser.py

Small fix to the top-parser to be able to parse martini itps again.

Top fix/martini topologies

---

README.md

Installation changes with the release and the system generation also needs one more required argument

Update Readme for first release

---

.travis.yml

this is the new api token with pypi ref

add new token and update pypi ref

---

polyply/data/martini2_polymers/links.ff
polyply/tests/test_data/gen_itp/input/DPPC.itp
polyply/tests/test_data/gen_itp/ref/PEL.itp

small edit to last PR fixing the naming of PC vs PE lipids.

adjust naming for PC/PE lipid head group

---

.github/workflows/pypi_deploy.yml
.github/workflows/python-app.yml

This is a first draft of using GH actions for testing with polyply.

GH actions for testing

---

bin/polyply
polyply/src/apply_links.py
polyply/src/gen_coords.py
polyply/src/generate_templates.py

Here is the long sought after logger.

implement Logger

---

setup.cfg

This should fix #127 until it gets patched in networkx.

Add decorator install criterion

---

polyply/src/gen_itp.py

add format specifier to disconnected molecule logging warning

---

bin/polyply
polyply/src/map_to_molecule.py
polyply/tests/test_map_to_molecule.py

Small bug, big effect. Now we can also deal with multiple blocks from itp files.

Fix multiple blocks from itp [1]

---

polyply/data/martini3/PSS.martini3.ff
run_pylint.py

PSS input file didn't produce the expected links because of wrong residue naming.

Patch PSS files

---

polyply/src/gen_itp.py

Adds a try except to keep compatibility with up-coming vermouth release.

fix change in deferred file writing

---

README.md

Polyply is now a featured article so I decided we can add a news section with recent publication and other stuff regarding polyply. Not sure anyone reads this but could be cool.

Add News section

---

polyply/src/persistence.py

Raise error/warning looking at the actual subsampled distribution. Fixes #203 and potentially #185

look at actual persistence length distribution before raising error

---

polyply/data/2016H66/polyvinyl_blocks.ff

The residue name in block PMAM was not correct for atom 6

FixType2016H66

---

bin/polyply

simple update to gen_params help text

add TXT FASTA and IG format to gen_params help text

---

.github/workflows/python-app.yml

add development branch to CI

---

.github/ISSUE_TEMPLATE/parameter-submission.md

Add issue template for parameter submission

Update issue templates

---

.github/workflows/pypi_deploy.yml
.github/workflows/python-app.yml

adjust CI to latest ubuntu version

adjust python versions

---

.codecov.yml
.github/workflows/pypi_deploy.yml
.github/workflows/python-app.yml

this should take care to ignore test files when dealing with coverage reporting

ignore tests with coverage

---

polyply/src/build_system.py
polyply/src/random_walk.py

Small optimisation for building large polymers and placing solvents.

Optimisation of Speed

---

polyply/src/persistence.py
polyply/tests/test_persistence.py

Adds missing brackets to parts of the worm_like_chain_model function

Fix wcm function

---

polyply/src/apply_modifications.py
polyply/src/generate_templates.py
polyply/tests/test_apply_modifications.py

correct the atomlist to handle different numbers of atoms in applied modification interaction

correct atomlist selection in apply_modifications.py

---

LIBRARY.md

Adding M3 cellulose to LIBRARY.md file, that is currently in the library but missing from that markdown file..

Add M3 cellulose to LIBRARY.md file
