marrink-lab/polyply_1.0

README.md

I fixed the command to show the available polymer libraries (`polyply -list-lib`) and links in the README (they linked to martinize2).

Fix few typos in README.md

---

polyply/src/apply_links.py
polyply/src/graph_utils.py
polyply/src/map_to_molecule.py
polyply/src/polyply_parser.py
polyply/src/topology.py
polyply/tests/test_apply_links.py
polyply/tests/test_data/gen_itp/input/test.ff
polyply/tests/test_data/gen_itp/ref/test_rev.itp
polyply/tests/test_graph_utils.py
polyply/tests/test_itp_gen.py
polyply/tests/test_polyply_input.py
polyply/tests/test_topology.py
requirements-tests.txt
setup.cfg

This PR bases apply links on a graph iso-morphism search at residue level, which fixes issue #78 . In addition it instead of looping over all interactions when one interaction is added newly, it first cashes them in a dict and overwrites interactions that have the same atom sequence and version. Furthermore it when looking up matching atoms it doesn't search the complete molecule anymore but just the residue corresponding to the meta-molecule node. Overall this cuts run-time by a factor of about 200 in complex cases.

Fast apply links

---

polyply/src/meta_molecule.py
polyply/tests/test_meta_molecule.py

Unfortunately with master the splitting of residues doesn't work. Resids are not uniquely assigned, which causes the back mapping to fail. This PR fixes the issue though it also slows down the process.

fix splitting function; properly generates new resids

---

polyply/data/martini2_polymers/links.ff
polyply/tests/test_data/gen_itp/input/PEO_PE.json
polyply/tests/test_data/gen_itp/output/PEO_b_PE_out.itp
polyply/tests/test_data/gen_itp/ref/PEO_PE_10.itp
polyply/tests/test_itp_gen.py

For now, I just added one more link to allow building of PEO-PE block copolymers, which seems to be necessary as explained in https://github.com/marrink-lab/polyply_1.0/issues/91.  More links, if needed, could be added as part of this pull request.

More link definitions for building block copolymers

---

polyply/data/martini2_polymers/citations.bib
polyply/src/gen_itp.py

I've added the DOIs to the bib entries - I think they make references more easy to find (and it works without problems!).
I also fixed a minor typo in `gen_itp.py`.
By the way, shall we get rid of the older headers, e.g, the following lines, now that citations are nicely taken care of?
https://github.com/marrink-lab/polyply_1.0/blob/2d21c2a6e777c4d2d41ccc5777bd3fb2b367667f/polyply/data/martini2_polymers/P3HT.martini.2.itp#L3-L16

Add DOIs to Martini 2 citations and fix typo in gen_itp.py

---

README.md

Minor stuff. What prompted me to do this small README update was mostly the fact that I found the following example code:
```
.... -box <x, y, z>
```
confusing as it seems to imply to pass `-box 10, 10, 10` while the correct command is `-box 10 10 10`.
I've also been going a bit through the wiki and I have some suggestions/edits but I'm unsure about how it works with pull requests and such for the wiki... It seems to be separate from the repo.

Small fixes to the main README file

---

setup.cfg

The default vermouth version is too old. People that have installed an older version will get an error. 0.7.1 works fine for me.

Fix vermouth dependency error

---

README.md

This new version of the Readme draws more attention to the wiki and migrates all essential information there. This keeps the front page more clean and allows us to fix simple problems in the tutorial/installation instructions without having to edit the Readme every time.
@ricalessandri and @pckroon could you give some general comments feedback?
Also together with this PR the following wiki pages have been created. Ideally someone check those as well. You should be able to edit and modify them as you see fit. Let me know if you have any issues:
https://github.com/marrink-lab/polyply_1.0/wiki/Quick-Start
https://github.com/marrink-lab/polyply_1.0/wiki/Installation
https://github.com/marrink-lab/polyply_1.0/wiki/Submit-polymer-parameters

Make the readme more streamline

---

polyply/src/gen_coords.py

This PR fixes a small logic bug in gen_coords regarding the ligand annotator. Instead of using the processor twice a new instance was generated when trying to split the ligands. That leads to incorrect behavior where the molecule is tagged twice with ligands. This blows up obviously. Tests for this fix are not within polyply but included in the new regression test suite, which will be subject to another PR.

Bug fix regarding the use of ligand annotator

---

polyply/src/gen_coords.py
polyply/src/restraints.py
polyply/tests/test_restraints.py

Restraints for generally branched molecules turns out to be somewhat more involved than what is presented in the draft. Therefore this PR is an mid-way fix which relaxes the branching conditions a little and yields an error when the restraint cannot be satisfied due to branching. It's not optimal but needed for the publication.

relax restraint check; allow for branched molecules in principle

---

polyply/src/check_residue_equivalence.py
polyply/tests/test_residue_check.py

Small bug fix for check residues. If molecules are defined in the top file but not used in the actual system the check results in an error while it should just skip that molecule.

skip  unused molecules in residue check

---

polyply/data/martini3/PMA.martini3.ff
polyply/data/martini3/PMMA.martini3.ff

Unimportant, just cosmetic but I just noticed so I figured why not fix it.

Fix small typo (vinly --> vinyl); cosmetic

---

polyply/tests/test_build_file_parser.py
polyply/tests/test_persistence.py

#187 fails due to an update of pytest. Because of this update the slightly weird `@staticmethod`'s cause issues. In addition, it turns out the way we used pytest.approx is wrong... I set the relative allowed error to `1e-3`. since I thought that makes sense.

Test failure

---

polyply/src/top_parser.py

Was getting this error:
```
OSError: Cannot find file /Users/riccardo/PD-UC/AA/polyply--reference/PH001_n30_opls_OK.itp. 
This can happen when you try to include force-field files from the GMX library (e.g. #incldue "gromos"). 
Instead provide the full path. Another source for this error can be that you have a #ifdef section 
with an #include but your include file does not exist. In that case if you don't have the file remove 
the #include statement.
```
and started to search for `#` statements and such... but it turned out that simply the path in my top was wrong (missing one subfolder...). So, I slightly edited the error message to put that - the simplest explanation for this error - as the first explanation. See if you like it.

Small improv error message top_parser

---

polyply/src/gen_itp.py
polyply/src/graph_utils.py
polyply/src/meta_molecule.py
polyply/tests/test_gen_params.py
polyply/tests/test_graph_utils.py

For the polyply GUI implementation in MAD a more detailed warning about missing edges should be raised. This is a first draft for this.

Raise more detailed warning about disconnected molecule

---

polyply/src/build_file_parser.py
polyply/src/generate_templates.py
polyply/src/topology.py
polyply/tests/test_build_file_parser.py
polyply/tests/test_generate_templates.py

Allows parsing and handling of volumes and residue templates. However, I don't like the mess of different processors setting hidden attributes. I think I'll get rid of the volumes and templates attribute of topology and meta-molecule and instead hand them down as processor arguments.

[2] Fix/237

---

polyply/src/apply_links.py
polyply/tests/test_apply_links.py
polyply/tests/test_data/gen_params/input/removal.ff
polyply/tests/test_data/gen_params/output/removal.itp
polyply/tests/test_data/gen_params/ref/removal.itp
polyply/tests/test_gen_params.py

In this PR we add molecule.interactions dict to the temporary dict in applied links. With that also interactions within a residue can be modified if need be. Also we add the option to remove nodes with the `'{'replace':'atomname': null}'` syntax as is the case for the vermouth applied links.

make sure self-links are applied

---

polyply/data/martini3/PTMA.martini3.ff
polyply/data/martini3/citations.bib
polyply/tests/test_data/library_tests/martini3/PTMA/polyply/PTMA.itp
polyply/tests/test_data/library_tests/martini3/PTMA/polyply/command
polyply/tests/test_lib_files.py

Contributing the Martini 3 CG model developed for PTMA in https://arxiv.org/abs/2209.02072.
Test to follow.

Add PTMA CG M3 model to polyply library [arXiv:2209.02072]

---

LIBRARY.md
README.md

I had this idea and wanted to run it with you, @fgrunewald. It might be useful to have this somewhere for users that want to know whether a certain polymer is already in the polyply library (without having to install polyply). It could then [be linked](https://github.com/ricalessandri/polyply_1.0/blob/library-table/LIBRARY.md) in the main README.
Let me know what you think, this is a draft so many things could be improved (including maybe automating the table generation...). But wanted to first check if this is of any interest.

Add a library table, i.e., list of models available in the polyply library

---

.gitignore
bin/polyply
polyply/src/gen_seq.py

Following #311 and #295, this PR:
- removes having to use -name in gen_coords
- gives a default output file name of `coords.gro` in gen_coords if `-o` is not specified
- includes @ricalessandri's error messaging in #295

Input cleaning

---

polyply/src/minimizer.py

small patch to counter deprecation error

add scipy 1.11 patch

---

polyply/src/top_parser.py
polyply/tests/test_top_parser.py

[1] Error pragma

---

LIBRARY.md
polyply/data/martini3/PTMA.martini3.ff
polyply/data/martini3/citations.bib

Update citation of Martini 3 PTMA model (from arxiv to Macromolecules paper). Also fixes a small formatting error in LIBRARY.md.

Update citation of Martini 3 PTMA model

---

.github/workflows/pypi_deploy.yml
.github/workflows/python-app.yml
polyply/data/martini3/aminoacids.ff

position restraint directives had too many parameters for each amino acid which caused problems on grompp

M3 aa posres fix

---

polyply/data/ol21/dna.ff
polyply/data/ol21/rna.ff

Improper dihedrals for maintaining chirality are now correctly added for all building blocks of DNA as well as all nucleosides.

Fixed impropers for chirality

---

polyply/src/simple_seq_parsers.py

Noticed we were missing the one letter code for HYP in the fasta parsing.
Once we fix #384 hopefully we can move the other AA modifications over to the modifications.ff file for the martini3 data for more consistency (and to actually be able to use them in polyply) (I will try to fix the modifications next week)

Extra aa code

---

bin/polyply
polyply/data/martini3/modifications.ff
polyply/src/apply_modifications.py
polyply/tests/test_apply_modifications.py
polyply/tests/test_data/library_tests/martini3/PROTMODS/polyply/HIS5_mods.itp
polyply/tests/test_data/library_tests/martini3/PROTMODS/polyply/command
polyply/tests/test_lib_files.py

- -mods flag now only read once for all modifications
- patch all molecule termini as proteins, so any modification in addition to these ones are also applied.
- add more modifications from vermouth to martini3 forcefield
- change logging level and fix tests as per #385

fixed modifcation parsing
